# Generated by Django 3.0.1 on 2020-01-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modsy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='goal',
            new_name='goals',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='room',
            new_name='rooms',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='style',
            new_name='styles',
        ),
    ]
