# Generated by Django 3.0.1 on 2020-01-06 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modsy', '0004_auto_20200106_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='design',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
