# Generated by Django 3.0.1 on 2020-01-07 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modsy', '0008_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='furn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='styles',
        ),
        migrations.CreateModel(
            name='UserRequirement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('furn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modsy.furniture')),
                ('goals', models.ManyToManyField(to='modsy.goal')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modsy.room')),
                ('styles', models.ManyToManyField(to='modsy.design')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modsy.user')),
            ],
        ),
    ]
