# Generated by Django 3.0.1 on 2020-01-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modsy', '0009_auto_20200107_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequirement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
