# Generated by Django 3.0.1 on 2020-01-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modsy', '0010_auto_20200107_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequirement',
            old_name='styles',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='userrequirement',
            old_name='furn',
            new_name='furniture',
        ),
        migrations.RenameField(
            model_name='userrequirement',
            old_name='goals',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='userrequirement',
            old_name='rooms',
            new_name='room',
        ),
    ]
