# Generated by Django 3.0.1 on 2020-01-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modsy', '0011_auto_20200107_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRequirement',
            new_name='User_Requirement',
        ),
    ]
